#!/bin/sh
IN="`$meshr/bin/uci get lucid.http.address`" #lucid
IN="$IN 2006 `bin/uci show olsrd| grep -E 'port=[0-9]+' | sed "s/.*port=//g"`" #olsrd
for port in $(echo "$IN" | tr " " "\n"); do
 if [  ]; then
  sudo iptables -C INPUT -i eth0 -p tcp --dport $port -j DROP ||  sudo iptables -A INPUT -i eth0 -p tcp --dport $port -j DROP
 else
  sudo iptables -C INPUT -i eth0 -p tcp --dport $port -j DROP &&  sudo iptables -D INPUT -i eth0 -p tcp --dport $port -j DROP 
 fi 
done